export const SET_HOT_FORUMS = 'SET_HOT_FORUMS';
export const SET_FEATURED_FORUMS = 'SET_FEATURED_FORUMS';
export const SET_HOT_POSTS = 'SET_HOT_POSTS';
export const SET_FORUM_POSTS = 'SET_FORUM_POSTS';
export const SET_CURRENT_FORUM = 'SET_CURRENT_FORUM';
